# Generated by Django 3.0.7 on 2021-06-09 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('LOL', 'League of Legends')], default='LOL', max_length=20)),
                ('positions_played', models.CharField(choices=[('Top', 'Top'), ('Jungle', 'Jungle'), ('Mid', 'Mid'), ('Bot', 'Bot'), ('Support', 'Support')], default='Top', max_length=7)),
                ('rank', models.CharField(choices=[('Challenger', 'Challenger'), ('GrandMaster', 'GrandMaster'), ('Master', 'Master'), ('Diamond', 'Diamond'), ('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('Iron', 'Iron')], default='Challenger', max_length=20)),
                ('server', models.CharField(choices=[('BR', 'BR(BRT)'), ('EUNE', 'EUNE(CEST)'), ('EUW', 'EUW(CEST)'), ('LAN', 'LAN(EDT)'), ('LAS', 'LAS(CLT)'), ('NA', 'NA(PST)'), ('OCE', 'OCE(AEST)'), ('RU', 'RU(CEST)'), ('TR', 'TR(TRT)'), ('JP', 'JP(JST)'), ('KR', 'KR(KST)'), ('CN', 'CN(CST)'), ('TW', 'TW(CST)'), ('SAM', 'SAM(SGT)'), ('VN', 'VN(ICT)'), ('TH', 'TH(ICT)'), ('PH', 'PH(PHST)')], default='NA', max_length=5)),
                ('start_Time_Available', models.TimeField()),
                ('end_Time_Available', models.TimeField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('in_Game_Name', models.CharField(max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
