# Generated by Django 3.0.7 on 2021-05-04 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('LOL', 'League of Legends')], default='LOL', max_length=20)),
                ('game_icon', models.CharField(default='/../staticfiles/LOL-logo.jpg', max_length=40)),
                ('positions_played', models.CharField(choices=[('Top', 'Top'), ('Jungle', 'Jungle'), ('Mid', 'Mid'), ('Bot', 'Bot'), ('Support', 'Support')], default='Top', max_length=7)),
                ('rank', models.CharField(choices=[('Challenger', 'Challenger'), ('GrandMaster', 'GrandMaster'), ('Master', 'Master'), ('Diamond', 'Diamond'), ('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('Iron', 'Iron')], default='Challenger', max_length=20)),
                ('server', models.CharField(choices=[('BR', 'BR'), ('EUNE', 'EUNE'), ('EUW', 'EUW'), ('LAN', 'LAN'), ('LAS', 'LAS'), ('NA', 'NA'), ('OCE', 'OCE'), ('RU', 'RU'), ('TR', 'TR'), ('JP', 'JP'), ('KR', 'KR'), ('CN', 'CN'), ('TW', 'TW'), ('SAM', 'SAM'), ('VN', 'VN'), ('TH', 'TH'), ('PH', 'PH')], default='NA', max_length=5)),
                ('start_Time_Available', models.CharField(choices=[('0', '0:00 (EST)'), ('1', '1:00 (EST)'), ('2', '2:00 (EST)'), ('3', '3:00 (EST)'), ('4', '4:00 (EST)'), ('5', '5:00 (EST)'), ('6', '6:00 (EST)'), ('7', '7:00 (EST)'), ('8', '8:00 (EST)'), ('9', '9:00 (EST)'), ('10', '10:00 (EST)'), ('11', '11:00 (EST)'), ('12', '12:00 (EST)'), ('13', '13:00 (EST)'), ('14', '14:00 (EST)'), ('15', '15:00 (EST)'), ('16', '16:00 (EST)'), ('17', '17:00 (EST)'), ('18', '18:00 (EST)'), ('19', '19:00 (EST)'), ('20', '20:00 (EST)'), ('21', '21:00 (EST)'), ('22', '22:00 (EST)'), ('23', '23:00 (EST)')], default='0', max_length=20)),
                ('end_Time_Available', models.CharField(choices=[('0', '0:00 (EST)'), ('1', '1:00 (EST)'), ('2', '2:00 (EST)'), ('3', '3:00 (EST)'), ('4', '4:00 (EST)'), ('5', '5:00 (EST)'), ('6', '6:00 (EST)'), ('7', '7:00 (EST)'), ('8', '8:00 (EST)'), ('9', '9:00 (EST)'), ('10', '10:00 (EST)'), ('11', '11:00 (EST)'), ('12', '12:00 (EST)'), ('13', '13:00 (EST)'), ('14', '14:00 (EST)'), ('15', '15:00 (EST)'), ('16', '16:00 (EST)'), ('17', '17:00 (EST)'), ('18', '18:00 (EST)'), ('19', '19:00 (EST)'), ('20', '20:00 (EST)'), ('21', '21:00 (EST)'), ('22', '22:00 (EST)'), ('23', '23:00 (EST)')], default='0', max_length=20)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('in_game_name', models.CharField(max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
