# Generated by Django 3.0.7 on 2021-05-12 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinfo',
            name='game_icon',
        ),
    ]
