# Generated by Django 3.0.7 on 2020-06-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_info', '0002_auto_20200621_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinfo',
            name='game',
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='positions_played',
            field=models.CharField(choices=[('top', 'Top'), ('jg', 'Jungle'), ('mid', 'Mid'), ('bot', 'Bot'), ('sup', 'Support')], default='top', max_length=3),
        ),
    ]
