# Generated by Django 3.0.7 on 2021-06-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_info', '0002_remove_gameinfo_game_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameinfo',
            old_name='in_game_name',
            new_name='in_Game_Name',
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='time_Zone',
            field=models.CharField(default='Test', editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='end_Time_Available',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='start_Time_Available',
            field=models.TimeField(),
        ),
    ]
