# Generated by Django 3.0.7 on 2020-06-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_info', '0003_auto_20200625_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='positions_played',
            field=models.CharField(choices=[('Top', 'Top'), ('Jungle', 'Jungle'), ('Mid', 'Mid'), ('Bot', 'Bot'), ('Support', 'Support')], default='Top', max_length=7),
        ),
    ]
