# Generated by Django 3.0.7 on 2021-06-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_info', '0003_auto_20210609_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinfo',
            name='time_Zone',
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='server',
            field=models.CharField(choices=[('BR', 'BR(BRT)'), ('EUNE', 'EUNE(CEST)'), ('EUW', 'EUW(CEST)'), ('LAN', 'LAN(EDT)'), ('LAS', 'LAS(CLT)'), ('NA', 'NA(PST)'), ('OCE', 'OCE(AEST)'), ('RU', 'RU(CEST)'), ('TR', 'TR(TRT)'), ('JP', 'JP(JST)'), ('KR', 'KR(KST)'), ('CN', 'CN(CST)'), ('TW', 'TW(CST)'), ('SAM', 'SAM(SGT)'), ('VN', 'VN(ICT)'), ('TH', 'TH(ICT)'), ('PH', 'PH(PHST)')], default='NA', max_length=5),
        ),
    ]
