# Generated by Django 3.0.7 on 2020-06-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_info', '0004_auto_20200625_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='game',
            field=models.CharField(choices=[('LOL', 'League of Legends')], default='LOL', max_length=20),
        ),
    ]
