# Generated by Django 3.0.7 on 2020-06-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_info', '0005_gameinfo_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='rank',
            field=models.CharField(choices=[('Challenger', 'Challenger'), ('GrandMaster', 'GrandMaster'), ('Master', 'Master'), ('Diamond', 'Diamond'), ('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('Iron', 'Iron')], default='Challenger', max_length=20),
        ),
    ]
