# Generated by Django 3.0.7 on 2020-06-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_info', '0006_gameinfo_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='server',
            field=models.CharField(choices=[('BR', 'BR'), ('EUNE', 'EUNE'), ('EUW', 'EUW'), ('LAN', 'LAN'), ('LAS', 'LAS'), ('NA', 'NA'), ('OCE', 'OCE'), ('RU', 'RU'), ('TR', 'TR'), ('JP', 'JP'), ('KR', 'KR'), ('CN', 'CN'), ('TW', 'TW'), ('SAM', 'SAM'), ('VN', 'VN'), ('TH', 'TH'), ('PH', 'PH')], default='NA', max_length=5),
        ),
    ]
