# Generated by Django 3.0.7 on 2020-06-25 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_info', '0007_gameinfo_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='time_available',
            field=models.TimeField(default=datetime.time(19, 39, 50, 861333)),
        ),
    ]
