# Generated by Django 3.0.7 on 2020-06-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_info', '0008_gameinfo_time_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinfo',
            name='time_available',
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='end_Time_Available',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23')], default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='start_Time_Available',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23')], default='0', max_length=20),
        ),
    ]
